version: "3"

services:
  web:
    build: .
#    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
